spring:
  application:
    name: mind-maze-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:7b
          temperature: 0.7
  datasource:
    url: jdbc:postgresql://localhost:5432/MINDMAZE
    username: mind_maze
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: metrics,info,prometheus
  endpoint:
    metrics:
      access: READ_ONLY
    prometheus:
      access: READ_ONLY
    info:
      access: READ_ONLY
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        all: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true

logging:
  level:
    root: info
    com.lpu.mind_maze_ai: debug
    org.springframework: info
    org.hibernate: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mind-maze.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/mind-maze-%d{yyyy-MM-dd}.log
      max-history: 30

info:
  application:
    name: ${spring.application.name}
    description: Mind Maze AI Application
    version: 1.0.0
  contact:
    name: Akash Thakur
    email: dev@mindmaze.com

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-should-be-very-long-and-secure}
  expiration: ${JWT_EXPIRATION:86400000}
